services:
  prod:
    build: 
      context: .
      dockerfile: Prod
    image: 4skl_blog
    volumes:
      - data-volume:/data
      - log-volume:/var/log
    command: ./start.sh
    ports:
      - "80:80" # on production server use <random port for nginx proxy>:80

  dev:
    build: 
      context: .
      dockerfile: Dev
    image: dev_4skl_blog
    volumes:
      - data-volume:/data
      - log-volume:/var/log
    command: ./start.sh
    ports:
      - "80:80" # on production server use <random port for nginx proxy>:80
volumes:
  data-volume:
  log-volume: