services:
  web:
    build: .
    image: 4skl_blog
    volumes:
      - data-volume:/data
      - log-volume:/var/log
    command: ./start.sh
    ports:
      - "80:80"

  db_save:
    image: 4skl_blog
    depends_on:
      - web
    volumes:
      - data-volume:/data
    command: sh -c "cd backend/ && python3 manage.py dumpdata > /data/backend_data.json" app
  
  db_load:
    image: 4skl_blog
    depends_on:
      - web
    volumes:
      - data-volume:/data
    command: sh -c "cd backend/ && python3 manage.py loaddata /data/backend_data.json" app

  media_save:
    image: 4skl_blog
    depends_on:
      - web
    volumes:
      - data-volume:/data
    command: sh -c "cp -r /var/www/4skl/media/ /data/" app
  
  media_load:
    image: 4skl_blog
    depends_on:
      - web
    volumes:
      - data-volume:/data
    command: sh -c "cp -r /data/media/ /var/www/4skl/" app

volumes:
  data-volume:
  log-volume: