version: '3.8'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    volumes:
      - ./skl_backend:/usr/src/blog.4skl.com/skl_backend
      - ./media:/var/www/blog.4skl.com/media
      - static_volume:/var/www/blog.4skl.com/static
    logging:
        options:
          max-size: '100m'
          max-file: '3'

  prod:
    depends_on:
      - django
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./media:/var/www/blog.4skl.com/media
      - static_volume:/var/www/blog.4skl.com/static
      - certbot_data:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    logging:
      options:
        max-size: '100m'
        max-file: '3'

volumes:
  static_volume:
  certbot_data: