version: '3.8'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    volumes:
      - ./skl_backend:/usr/src/4skl.com/skl_backend
      - ./media:/var/www/4skl.com/media
      - static_volume:/var/www/4skl.com/static
  
  prod:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./media:/var/www/4skl.com/media
      - static_volume:/var/www/4skl.com/static
    ports:
      - 80:80
    depends_on:
      - django

volumes:
  static_volume: