version: '3'
services:
  django:
    build:
      context: ../skl_backend
      dockerfile: Dockerfile.django
    volumes:
      - ../skl_backend:/usr/src/app
    ports:
      - 8000:8000
  vue:
    build:
      context: ../4skl
      dockerfile: Dockerfile.vue
    volumes:
      - ../4skl:/usr/src/app
    ports:
      - 3000:3000
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ../skl_backend:/usr/src/app/skl_backend
      - ../4skl:/usr/src/app/4skl
    depends_on:
      - django
      - vue