version: '3'
services:
  django:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.django
    volumes:
      - ../skl_backend:/usr/src/app/skl_backend
    ports:
      - 8000:8000
  vue:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.vue
    volumes:
      - ../4skl:/usr/src/app/4skl
    ports:
      - 3000:3000
  dev:
    image: alpine
    command: ["sh", "-c", "while true; do sleep 86400; done"]
    volumes:
      - ../skl_backend:/usr/src/app/skl_backend
      - ../4skl:/usr/src/app/4skl
    depends_on:
      - django
      - vue